### ISSUE TITLE
vscode windows 10 with WSL2

### ISSUE THREAD

**Issue by th3g3ntl3men** [42Crunch/vscode-openapi#104]
Ok so my machine is windows 10 ARM and I run WSL2 for my environment. 

using $ref to a local file inside of WSL2 fails to resolve. 

api.yaml

```yaml
openapi: 3.0.0
info:
  description: my desc
  version: '1.0.0'
  title: API
paths:
  /v1/something:
    post:
      tags:
        - something
      summary: do something
      operationId: myOPId 
      responses:
        201:
          $ref: 'responses.yaml#/CreatedDefault'
```
responses.yaml
```yaml
CreatedDefault:
  description: Record created
  content:
    application/json:
      schema:
        type: 'object'
        additionalProperties: false
        properties:
          uuid:
            type: string
            format: uuid
          created_ts:
            type: string
            format: date-time
```
Inside of WSL I get the error : `failed to resolve //wsl/$/kali-linux/home/user/project/src/apis/v1/responses.yaml`

**Comment by ak1394** [comment]
Thanks for the report! When the plugin tries to resolve external reference, it uses base document URL as a starting point. So could you check what is the path to your main OpenAPI document (the one at the top) and what is the proper path for responses.yaml if you ls it from inside WSL?

**Comment by th3g3ntl3men** [comment]
This is the windows path to the file 
`//wsl/$/kali-linux/home/user/project/src/apis/v1/responses.yaml` 
inside of wsl it should just be `~/project/src/apis/v1/responses.yml`

But thinking about this, I execute `code .` from inside of WSL but visual studio is running on the windows file system. 
So my initial idea would be a setting variable (you could just override the base path for ex.).

**Comment by ak1394** [comment]
The extension uses original document's URI (it takes document.uri.fsPath) to come up with the base folder to resolve references from. So I wonder if document.uri.fsPath is wrong under WSL?

**Comment by th3g3ntl3men** [comment]
Could be, but wouldn't that affect vs code?

**Comment by ak1394** [comment]
Well, it depends on how the document URI is used in VS Code. It would be a good idea to try to check what document URI is in the first place. Can you check out the extension source, set a breakpoint and run it?

**Comment by th3g3ntl3men** [comment]
Yeah I can do that.

**Comment by ak1394** [comment]
Sure, whenever you have time. Once you clone the project (please checkout tag "v3.10.0", run "npm install" and then "npm run vscode:prepublish" in the root folder. Then you should be able to open it in VS Code, set a breakpoint at src/bundler.ts:62 and run it. Try displaying the preview for your file, and it should hit the breakpoint. In there "documentUri" would be the main document URI (I wonder what's the value is, and what's the "documentUri.fsPath" is, and "uri" is the URI of the document it fails to find under WSL.

**Comment by th3g3ntl3men** [comment]
Thanks for the quick user guide :) I'll get back to you this week.

**Comment by ClappTrap** [comment]
I tried to get this debugging working. I was able to clone, build and execute debugging. But now when I open the folder in WSL it crashes with no warnings. Idk if there logs, if there are it doesn't tell me where.

**Comment by ak1394** [comment]
Well, you managed to get quite far in trying to debug it. If the VS Code crashes though, it's probably something to do with VS Code / WSL compatibility. I haven't seen it crashing, so I don't have much of advise on how to troubleshoot it (apart from maybe opening an issue in https://github.com/microsoft/vscode/ ) We'll try to run debugging under WSL to see if it happens to us as well.

**Comment by ClappTrap** [comment]
Sounds good, i am gonna play around with it some more as time permits. If I get further I'll let you know.

**Comment by stevegoossens** [comment]
> The extension uses original document's URI (it takes document.uri.fsPath) to come up with the base folder to resolve references from. So I wonder if document.uri.fsPath is wrong under WSL?

The problem is that the WSL2 paths for `$ref` relative file paths are being generated with a `/` after the "wsl" and before the `$` (escaped as `%24`). Here is a more detailed description:

**What happened?**

All OpenAPI yaml files that have `$ref` values pointing at a relative "external" OpenAPI yaml file have the WSL2 `file://` path generated with an extraneous `/` character after the "wsl", e.g.

`file://wsl/%24/Ubuntu-20.04/home/steve/github/bbc/account-service-contract/openapi/base.yaml`

This filepath is NOT valid in Windows Explorer, and nothing loads when pasting it into Windows Explorer address bar and pressing Enter.

**What should have happened instead?**

The WSL2 file locations should be generated _without_ the `/` character following "wsl", e.g.

`file://wsl%24/Ubuntu-20.04/home/steve/github/bbc/account-service-contract/openapi/base.yaml`

This file URL _is_ valid in Windows Explorer, and pasting this into its address bar and pressing Enter produces an Open File With dialog window, including the option to open in VS Code, which successfully opens.

**Minimal reproducible OpenAPI snippet**

`main-example.yaml`
```
openapi: '3.0.0'
info:
  title: '@project.name@'
  version: '@project.version@'
  description: main
servers:
  - url: http://localhost:8080
    description: Local development (Spring Boot)
paths:
  /v3/user/association:
    post:
      tags:
        - user
      summary: Create user association
      parameters:
        - $ref: 'base-example.yaml#/components/parameters/headerXray'
      description: The ref above currently generates a malformed WSL2 path in Redocly extension
      operationId: association
      responses:
        '204':
          description: Success. The account association was created.
```

`base-example.yaml`
```
openapi: '3.0.0'
info:
  description: blah
  version: '@project.version@'
  title: '@project.name@'
servers:
  - url: http://localhost:8080
    description: Local development (Spring Boot)
paths:
  /placeholder:
    get:
      summary: Placeholder
      description: |
        This is just a pretend API endpoint to satisfy the OpenAPI spec of having at least one
        URI path. It is **NOT** a real API path.
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: dummy
components:
  parameters:
    headerXray:
      name: x-amzn-trace-id
      in: header
      description: "**Automatically Generated** upstream (if AWS X-Ray is enabled)"
      schema:
        type: string
```

**Screenshots**

This results in errors for all WSL2 paths in `$ref` values, e.g.

![redoc-vscod-extension-wsl2-ref-path-error-example](https://user-images.githubusercontent.com/2405344/155715614-9ebe4bf9-5b03-448f-8c56-cbc3973e529b.png)

You can see that the Windows UNC path is resolved to `\\wsl\$\Ubuntu-20.04\home\steve\github\bbc\account-service-contract\openapi\base-example.yaml` which is _incorrect_ and should be `\\wsl$\Ubuntu-20.04\home\steve\github\bbc\account-service-contract\openapi\base-example.yaml`.

**Additional context**

VS Code is the Windows application. My OpenAPI project is on a Ubuntu filesystem in a WSL2 installation.

```
OpenAPI (Swagger) Editor, Version 4.9.1 (Feburary 23, 2022)

Released on
10/06/2019, 13:12:23
Last updated
23/02/2022, 14:48:35
Identifier
42crunch.vscode-openapi
```

```
PS C:\Users\steve> wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
docker-desktop-data
docker-desktop
```

```
Edition	Windows 10 Pro
Version	21H1
Installed on	‎27/‎06/‎2021
OS build	19043.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0
```

**Comment by stevegoossens** [comment]
Of note:

- VS Code (Windows) can access all files in the WSL2 Ubuntu file system.
- The same OpenAPI project, containing multiple yaml files referencing other yaml files in the same folder _does work_ in VS Code (Mac) where there is no WSL2 file system "complexity"
- If you remove just the `/` character after the "wsl" in the generated paths, it becomes valid in Windows Explorer and will almost certainly also work for this extension.

**Comment by stevegoossens** [comment]
I take it this is where the filepath is being generated?

https://github.com/42Crunch/vscode-openapi/blob/f8860399081baf5b8ef6fd019d481c4b9f9a342b/src/reference.ts#L25-L31

**Comment by stevegoossens** [comment]
`currentDocumentUri` appears to originate from `vscode.document.uri` in the callers

so it looks like either _that_ or `currentDocumentUri.fsPath` (so `vscode.document.uri.fsPath`) is causing the extraneous `/` to be added

**Comment by stevegoossens** [comment]
I just installed VS Code in Ubuntu, launched it and installed this extension, and the same OpenAPI project with multiple files (including the `$ref` to other yaml files) works correctly. So, for me at least:

- VS Code (Mac) + this extension with project files on normal MacOS fs: `$ref` paths resolve ✔️ 
- VS Code (deb) + this extension with project files on Ubuntu WSL fs: `$ref` paths resolve ✔️ 
- VS Code (Windows) + this extension with project files on Ubuntu WSL fs: `$ref` paths are malformed ❌

**Comment by stevegoossens** [comment]
@golden-protocol as a temporary workaround in the meantime, if you haven't already found this method, you can:

- install the Linux release of VS Code in Ubuntu
- install `VcXsrv` in Windows
- launch `VcXsrv` by double-clicking a config file, here's mine:

`config.xlaunch`
```
<?xml version="1.0" encoding="UTF-8"?>
<XLaunch WindowMode="MultiWindow" ClientMode="NoClient" LocalClient="False" Display="-1" LocalProgram="xcalc" RemoteProgram="xterm" RemotePassword="" PrivateKey="" RemoteHost="" RemoteUser="" XDMCPHost="" XDMCPBroadcast="False" XDMCPIndirect="False" Clipboard="True" ClipboardPrimary="True" ExtraParams="" Wgl="True" DisableAC="True" XDMCPTerminate="False"/>
```

- run `code` from Linux shell (this will spawn an application window in WIndows with the LInux VS Code)
- install the OpenAPI extension
- have all the `$ref` paths "just work"

**Comment by ak1394** [comment]
@stevegoossens Thanks for the detailed info. I don't have a WSL env handy at the moment, and I wonder if you'd be willing to test a version with a proposed fix? I can tweak the way the baseDir is made, to see if it would have any effect on it.

**Comment by stevegoossens** [comment]
yeah definitely, just let me know how to install the test version and I can give it a go

I did clone the repo and attempted to debug the extension to a breakpoint, but I've not done that before and got some errors about some files like generated/something.json and root/something else... I think that's just my lack of knowledge on debugging an extension though... 

if checking a test version is more along the lines of install it instead of the normal version and see if it works then I can do that much!

**Comment by ak1394** [comment]
Thanks for giving it a go, the problem is not your lack of knowledge but rather lack of instructions for preparing extension for debug, which we should provide. If you want to try debugging it again, just run `npm run install-deps` and `npm run vscode:prepublish` in the extension folder before trying to debug.

In any case, here is a pre-built extension package, which you should be able to install by going to "Extensions" clicking on three dots to bring up a menu and choosing "Install from VSIX..." (Please remove .zip extension from the file, as Github doesn't supporting .vsix files, it should be called `vscode-openapi-4.9.2-BETA1.vsix`)

If you want to grab source code with the change, it's on the `wsl_ref` branch in this repo.
[vscode-openapi-4.9.2-BETA1.vsix.zip](https://github.com/42Crunch/vscode-openapi/files/8145523/vscode-openapi-4.9.2-BETA1.vsix.zip)

**Comment by stevegoossens** [comment]
Cool, thanks for putting this together so quickly, I'll probably test it during the week like maybe Monday.

The commit looks promising and cleaner than the hacky way I was thinking like

```
if (baseUrl.contains('wsl/') {
  baseUrl.replace('wsl/', 'wsl')
}
```

maybe that can be a plan B if the posix/path stuff doesn't work as desired 😁

**Comment by stevegoossens** [comment]
Also, thanks for the debug instructions, I might give that a go if the beta doesn't work to breakpoint inspect

**Comment by stevegoossens** [comment]
Hmm, I just tried the beta extension (after uninstalling the marketplace version) and get the same error:
![beta-same-error](https://user-images.githubusercontent.com/2405344/155988323-c7d84e84-d705-4906-a8f7-fa71f7f972c0.png)

I'll see if i can get debug mode to work...

**Comment by ak1394** [comment]
Thanks for an update! This was a blind fix in a way, I was hoping that switching away from platform-dependent fsPath to using URL path would solve the issue, but evidently it did not. I'll poke around it some more and will try do another fix. 

In the meantime, if you want to try debugging it, go ahead and let me know if you need any more info.

**Comment by stevegoossens** [comment]
I'm trying to debug the extension from source and ran both `npm run` commands which appeared to work correctly, then from VS Code with `reference.ts` open in a tab, I go to the Run and Debug left nav icon to open that left panel, and click "Run and Debug" (the first time i think it prompted for a debug option so i chose the Extension one), and that spawns a second VS Code window.

I opened up my project folder (git repo cloned) containing the OpenAPI in the second window and can see the following error in the first VS Code window's Debug Console panel:

```
Unknown (FileSystemError) (FileSystemError): Error: UNKNOWN: unknown error, stat '\\wsl$\wsl$\Ubuntu-20.04\home\steve\github\bbc\account-service-contract\.git\config'
	at Function._handleError ([c:\Users\steve\AppData\Local\Programs\Microsoft]() VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:84319)
	at Object.stat ([c:\Users\steve\AppData\Local\Programs\Microsoft]() VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:82247)
	at processTicksAndRejections (<node_internals>/internal/process/task_queues.js:93:5)
	at async Object.isFile ([c:\Users\steve\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:453:27683]())
	at async gw ([c:\Users\steve\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:248:312]())
	at async PA ([c:\Users\steve\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:248:1076]())
	at async $1 ([c:\Users\steve\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:416:12437]())
	at async JC ([c:\Users\steve\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:416:12215]())
	at async GV ([c:\Users\steve\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:519:8352]())
	at async [c:\Users\steve\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:518:12773]() {code: 'Unknown', name: 'Unknown (FileSystemError) (FileSystemError)', stack: 'Unknown (FileSystemError) (FileSystemError): …0.217.4\dist\extension\extension.js:518:12773', message: 'Error: UNKNOWN: unknown error, stat '\\wsl$\…ub\bbc\account-service-contract\.git\config''}
arg0:Unknown (FileSystemError) (FileSystemError): Error: UNKNOWN: unknown error, stat '\\wsl$\wsl$\Ubuntu-20.04\home\steve\github\bbc\account-service-contract\.git\config'
	at Function._handleError ([c:\Users\steve\AppData\Local\Programs\Microsoft]() VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:84319)
	at Object.stat ([c:\Users\steve\AppData\Local\Programs\Microsoft]() VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:82247)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Object.isFile ([c:\Users\steve\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:453:27683]())
	at async gw ([c:\Users\steve\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:248:312]())
	at async PA ([c:\Users\steve\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:248:1076]())
	at async $1 ([c:\Users\steve\.vscode\extensions\ms-vsc...]()
code:'Unknown'
name:'Unknown (FileSystemError) (FileSystemError)'
message:'Error: UNKNOWN: unknown error, stat '\\\\wsl$\\wsl$\\Ubuntu-20.04\\home\\steve\\github\\bbc\\account-service-contract\\.git\\config''
stack:'Unknown (FileSystemError) (FileSystemError): Error: UNKNOWN: unknown error, stat '\\\\wsl$\\wsl$\\Ubuntu-20.04\\home\\steve\\github\\bbc\\account-service-contract\\.git\\config'\n\tat Function._handleError ([c:\\Users\\steve\\AppData\\Local\\Programs\\Microsoft]() VS Code\\resources\\app\\out\\vs\\workbench\\services\\extensions\\node\\extensionHostProcess.js:93:84319)\n\tat Object.stat ([c:\\Users\\steve\\AppData\\Local\\Programs\\Microsoft]() VS Code\\resources\\app\\out\\vs\\workbench\\services\\extensions\\node\\extensionHostProcess.js:93:822…:\\Users\\steve\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.217.4\\dist\\extension\\extension.js:416:12437)\n\tat async JC ([c:\\Users\\steve\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.217.4\\dist\\extension\\extension.js:416:12215]())\n\tat async GV ([c:\\Users\\steve\\.vscode\\extensions\\ms-vscode-remote.remote-containers-0.217.4\\dist\\extension\\extension.js:519:8352]())\n\tat async [c:\\Users\\steve\\.vscode\\extensions\\ms-vscode-remote.remote-c...]()
__proto__:m
<anonymous> @ c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5:6
```

The `\\\\wsl$\\wsl$\\Ubuntu-20.04\\home\\steve\\github\\bbc\\account-service-contract\\.git\\config` looks like it's doubling up on the wsl protocol prefix for some reason, not sure why it affects `./git/config` though?

**Comment by stevegoossens** [comment]
![debug-mode-no-intellisense-maybe](https://user-images.githubusercontent.com/2405344/155990903-efc12e42-5328-445f-9216-4e3e7a83f713.png)

in debug mode, the in-spec refs have working links, but the external file ref links aren't clickable

also, there's no openapi extension button in the left nav in debug mode, is that normal/expected?

**Comment by ak1394** [comment]
It's surprising you had to create a configuration to start a debuging session. There is .vscode/launch.json file in the repo which has a config called "Launch" which we normally use to debug the extension. You may want to look at launch.json to compare settings you've created and the "Launch" one.

As you've figured out in the comment above, it looks like it didn't launch the debug session correctly.

Also, the exceptions above are not related to our extension, but rather some VS Code (source control?) related one, which might hint that your WSL config is somehow problematic to VS Code.

So, if you want to continue try to sort out debug config, and you should at least see OpenAPI extension icon in the toolbar with basic functionality of the extension working, then you can move further in and try to look at reference.ts

**Comment by stevegoossens** [comment]
It wasn't a configuration, but rather the option to launch the debugging in Chrome, Node.js, Extension Development Host... i chose the Extension option, should I have chosen just Node.js?

**Comment by stevegoossens** [comment]
I'm trying opening your repo as the only folder in the VS Code workspace now to see if it loads the `.vscode/launch.json`

**Comment by ak1394** [comment]
Yeah, that's sounds right. Go File -> Open choose folder with the extension. When you click on "Run and Debug" icon in the left bar, you should see a dropdown on top with three configurations, "Launch", "Extension Tests" and "Launch Schema Gen Program". Choose "Launch" and hit start debugging button next to it.

**Comment by stevegoossens** [comment]
I read the MS docs about how to debug a VSCode extension for WSL and it mentions launching a new Remote WSL window to open up the extension folder/project, and then launch the debug from there which spawns another Remote WSL window in which i can open OpenAPI files with relative external file links in the `$ref` values and it all works.

With that "just works" bit successful, I then thought, how about just launching the new Remote WSL window for VS Code, with the regular marketplace OpenAPI extension installed, and guess what? It works correctly without all the `$ref` value errors, and Ctrl + hover gives the Intellisense (?) view, and Ctrl + click opens up the referenced file at that component.
![remote-wsl-openapi-works](https://user-images.githubusercontent.com/2405344/156404893-e354f302-e1a3-44a0-9302-3960751f8bef.png)

So:

## Use case 1: VS Code (Windows) in Remote WSL mode
- `Open Folder...` spawns an app modal window file system navigation in the top-middle of the app, in the WSL Linux filesystem
- this can open up a folder containing the OpenAPI files
- the extension works correctly ✔️ 

## Use case 2: VS Code (Windows) in regular mode
- `Open Folder...` spawns Windows Explorer dialog window to choose folder and shows the regular Windows filesystem as seen in Windows Explorer
- I open up a Linux folder by typing `\\wsl$` in the dialog window address bar which then lists my WSL distros, i can click through to it to browse through its filesystem
- the extension gives Problems errors for all `$ref` links ❌

**Comment by stevegoossens** [comment]
I think perhaps the issue might be that in order for this (or any other) extension to work with the WSL filesystem correctly, VS Code has to be in the Remote WSL mode rather than the regular mode.

**Comment by ak1394** [comment]
@stevegoossens Thanks a lot for tracking it down! This is might indeed be a case, and even if it is not, this is a very good workaround for the WSL problem. I'll leave the github issue open for the time being, but with your permission I'll add workaround instructions to the README.

**Comment by stevegoossens** [comment]
Of course, I'm not sure if it's a workaround or just the correct way of using VS Code in Windows with projects in WSL (it seems pretty acceptable/likely), but a note in an FAQ section or whatever could be useful.

**Comment by ak1394** [comment]
Looks like Remote WSL is indeed a correct way of using it, per description on Remote WSL page: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl 

I'll leave this issue open for now, till the change to README is made.
