### ISSUE TITLE
Plugin does not start due to error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by MiltiadisKoutsokeras** [42Crunch/vscode-openapi#280]
Hello,

I am using the `42Crunch.vscode-openapi` plugin with [VSCodium](https://vscodium.com/) version `1.92.2` and I get the following errors on extension activation:

```
2024-09-03 11:30:58.295 [error] Error: Cannot find module 'semver'
Require stack:
- /home/user/.vscode-oss/extensions/42crunch.vscode-openapi-4.28.1-universal/out/extension.js
- /usr/share/codium/resources/app/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
	at i._resolveFilename (node:electron/js2c/utility_init:2:13405)
	at Module._load (node:internal/modules/cjs/loader:993:27)
	at c._load (node:electron/js2c/node_init:2:13801)
	at w._load (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:177:7371)
	at i._load (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:38745)
	at o._load (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:139:44377)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at g (/usr/share/codium/resources/app/out/bootstrap-fork.js:2:647)
	at Object.<anonymous> (/home/user/.vscode-oss/extensions/42crunch.vscode-openapi-4.28.1-universal/out/extension.js:33:29)
	at u._compile (/usr/share/codium/resources/app/out/bootstrap-fork.js:2:1257)
	at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
	at Module.load (node:internal/modules/cjs/loader:1215:32)
	at Module._load (node:internal/modules/cjs/loader:1031:12)
	at c._load (node:electron/js2c/node_init:2:13801)
	at w._load (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:177:7371)
	at i._load (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:38745)
	at o._load (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:139:44377)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at require (node:internal/modules/helpers:179:18)
	at Function.i [as __$__nodeRequire] (/usr/share/codium/resources/app/out/bootstrap-fork.js:3:98)
	at m._loadCommonJSModule (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:40372)
	at async Promise.all (index 0)
```

The plugin does not work at all, I noticed the problem because I could not go to a definitions of my OpenAPI Spec YAML. Any ideas what to do about it?

Versions in detail:
42Crunch.vscode-openapi: `v4.28.1`
redhat.vscode-yaml: `v1.15.0`
VSCodium: `1.92.2`
Node: `v18.20.2`
NPM: `10.5.0`
OS: Debian 11

I am using nvm for managing node installations.

**Comment by ak1394** [comment]
Thanks for reporting the issue! It's been a while since we've tested on VSCodium, perhaps something changed in the recent versions. I'll update this issue once I know more.

**Comment by ak1394** [comment]
Thanks for letting me  know. The plugin includes the `semver` dependency, so the issue must be somewhere else. Since it did not reoccur, let's close it for now, but feel free to re-open it if it happens again.
